### ISSUE TITLE
[Issue] Export falsely completing

### ISSUE THREAD

**Issue by 3raxton** [jonwomack/snapchat-memory-exporter#1]
## Issue Overview

Hey @jonwomack, thanks for open sourcing your work! I'm eager to see how this could help me in my export process, however, I'm running into some issues with it. I've followed your README as closely as I can but I'm not quite sure if I'm doing this correctly. 

When running the command `python snapchat_export.py ./snapchat-downloads`, Terminal responds with `Exporting snapchat memories: 0media [00:00, ?media/s]`. 

I've noted that when downloading memories from Snapchat, they've changed the folder structure and you need to take separate steps to download `memories_history.json`.  I have this file but it is not part of the folders that came with this export. 

Another note, I am using Python 13.3, I updated `requirements.txt` to include `Pillow` at `11` rather than`10.3` as I cannot get pip to install Pillow 10.3. I can elaborate on this if needed, traceback follows if interested:

<details><summary>Details for issues with Pillow==10.3.0</summary>
<p>

```
$ uv pip install -r requirements.txt
Resolved 17 packages in 19ms
  × Failed to download and build `pillow==10.3.0`
  ╰─▶ Build backend failed to determine requirements with `build_wheel()` (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
          requires = get_requires_for_build({})
        File
      "/Users/Prized/.cache/uv/builds-v0/.tmp2Gsds7/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File
      "/Users/Prized/.cache/uv/builds-v0/.tmp2Gsds7/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File
      "/Users/Prized/.cache/uv/builds-v0/.tmp2Gsds7/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 33, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
```
</p>
</details> 

In other instances, I run into an issue when running `python snapchat_export.py ./snapchat-downloads`. I've made it past this point a few different times but it's something I figured I'd mention:

<details><summary>Details for issue with NumPy</summary>
<p>

`python3 snapchat_export.py ./snapchat-downloads `

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/Prized/github/snapchat-memory-exporter/snapchat_export.py", line 3, in <module>
    import cv2
  File "/usr/local/lib/python3.13/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.13/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/Users/Prized/github/snapchat-memory-exporter/snapchat_export.py", line 3, in <module>
    import cv2
  File "/usr/local/lib/python3.13/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
    ~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/local/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import
```
</p>
</details>  

> [!NOTE]
> I have no idea how to resolve this and would appreciate any insight you can provide me with 

**Thank you for your help and insight, I appreciate it!**

---

## Folder Structure

I believe my folder structure follows yours correctly, it follows and has some differences as I cloned the repo:

```
snapchat-memory-exporter
├── images
│   ├── export-step1.png
├── README.md
├── requirements.txt
├── snapchat-downloads
│   ├── mydata~1726676521421
│      ├── chat_media
│      ├── html
│      ├── index.html
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-1
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-2
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-3
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-4
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-5
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-6
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-7
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-8
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-9
│      ├── chat_media
│      ├── memories
│      ├── shared_story
│   ├── mydata~1726676521421-10
│      ├── chat_media
│      ├── memories
│      ├── shared_story
└── snapchat_export.py
```

**Comment by 3raxton** [comment]
Quick note, to resolve the issue with NumPy, I run `pip install --break-system-packages opencv-python` (I know this is aa poor practice, my Python structure on my Mac is in an awful state and I do not know ho to fix it). This allows me to successfully execute the command which results in the following output:

`Exporting snapchat memories: 0media [00:00, ?media/s]`

**Comment by 3raxton** [comment]
I managed to get Pillow 10.3.0 installed in a virtual environment and this is the output that I receive: 

```
$ python snapchat_export.py ./snapchat-downloads 
/Users/Prized/hitgub/snapchat-memory-exporter/.venv/lib/python3.12/site-packages/moviepy/config_defaults.py:1: SyntaxWarning: invalid escape sequence '\P'
  """
/Users/Prized/hitgub/snapchat-memory-exporter/.venv/lib/python3.12/site-packages/moviepy/video/io/ffmpeg_reader.py:294: SyntaxWarning: invalid escape sequence '\d'
  lines_video = [l for l in lines if ' Video: ' in l and re.search('\d+x\d+', l)]
/Users/Prized/hitgub/snapchat-memory-exporter/.venv/lib/python3.12/site-packages/moviepy/video/io/ffmpeg_reader.py:367: SyntaxWarning: invalid escape sequence '\d'
  rotation_lines = [l for l in lines if 'rotate          :' in l and re.search('\d+$', l)]
/Users/Prized/hitgub/snapchat-memory-exporter/.venv/lib/python3.12/site-packages/moviepy/video/io/ffmpeg_reader.py:370: SyntaxWarning: invalid escape sequence '\d'
  match = re.search('\d+$', rotation_line)
```
```
Exporting snapchat memories: 0media [00:00, ?media/s]
```

The folder structure for this environment is using a different download with a `json` folder. The folder structure looks like this: 

```
snapchat-memory-exporter
├── images
│   ├── export-step1.png
├── README.md
├── requirements.txt
├── snapchat_export.py
└── snapchat-downloads
│   ├── mydata~1731726678219
│      ├── chat_media
│      ├── html
│      ├── index.html
│      ├── json
│            ├── memories_history.json (and a ton of other files)
│      ├── memories
│──────├── shared_story
 
```

**Comment by jonwomack** [comment]
Hi @3raxton,

Can you share the output of this command
```
cd /Users/Prized/hitgub/snapchat-memory-exporter/
ls -R * | grep "memories.html"
```

And the structure of memories_history.json
```
cd /Users/Prized/hitgub/snapchat-memory-exporter/snapchat-downloads/mydata~1731726678219/json
head -n 20 memories_history.json

**Comment by 3raxton** [comment]
Hey there,

I can’t properly share the entire output because of how long it is but from what I can see it does get pretty specific with location, lat and long and links. Imagine the callback with about 50 of these links displayed. Let me know if this helps.

```
{"Date":"2016-07-13 10:48:46 UTC","Media Type":"Image","Location":"Latitude, Longitude: 39.322067, -94.72051","Download Link":"https://app.snapchat.com/dmd/memories?uid=966e77c2-8662-4379-9195-ba4f7172606a&sid=EB5C6C22-2C5A-45BF-B843-80F89F287B38&mid=C1ADBB5D-7DB2-45BD-946C-CBA23E3534A6&ts=1731736874702&proxy=true&sig=3f56169d10578ff65a9e0fdbac2f22330bc63ec5c9f5d59df5b8af436dccba1b";},{"Date":"2016-07-13 10:48:33 UTC","Media Type":"Image","Location":"Latitude, Longitude: 39.322067, -94.72051","Download Link":"https://app.snapchat.com/dmd/memories?uid=966e77c2-8662-4379-9195-ba4f7172606a&sid=A390D9EB-61ED-457C-9639-52C7162526A4&mid=88597B56-4C31-4C49-969A-5BDE3C992C4C&ts=1731736660508&proxy=true&sig=7bc1da49c8cdf151ab21bf72b594a651102d169df9d5d7493e2811cd3d29383b";},{"Date":"2016-07-13 10:48:33 UTC","Media Type":"Image","Location":"Latitude, Longitude: 39.322067, -94.72051","Download Link":"https://app.snapchat.com/dmd/memories?uid=966e77c2-8662-4379-9195-ba4f7172606a&sid=88597B56-4C31-4C49-969A-5BDE3C992C4C&mid=88597B56-4C31-4C49-969A-5BDE3C992C4C&ts=1731736586195&proxy=true&sig=7e0376b2d845c2990dfaf086bc31dc5fbc42b3657627930019bb7acd8f33c6fa";},{"Date":"2016-07-12 03:52:46 UTC","Media Type":"Video","Location":"Latitude, Longitude: 39.131744, -95.715866","Download Link":"https://app.snapchat.com/dmd/memories?uid=966e77c2-8662-4379-9195-ba4f7172606a&sid=1C3D8B07-526C-46E4-8F75-07347925EA1B&mid=1C3D8B07-526C-46E4-8F75-07347925EA1B&ts=1731736281085&proxy=true&sig=14489ffd23feaa64cccb3e0d76cc5602c8c88164123e968767a8b21d78f5cdb5";},{"Date":"2016-07-12 03:52:15 UTC","Media Type":"Video","Location":"Latitude, Longitude: 39.132137, -95.716896","Download Link":"https://app.snapchat.com/dmd/memories?uid=966e77c2-8662-4379-9195-ba4f7172606a&sid=1A974B3D-4841-4B9E-8B6D-52575E42A66B&mid=1A974B3D-4841-4B9E-8B6D-52575E42A66B&ts=1731736277182&proxy=true&sig=5f07a324aa17c594b8ccd4d50e8461ccf739eaebf1349730de47e1a2e9d2e877";},{"Date":"2016-07-06 03:40:40 UTC","Media Type":"Image","Location":"Latitude, Longitude: 0.0, 0.0","Download Link":"https://app.snapchat.com/dmd/memories?uid=966e77c2-8662-4379-9195-ba4f7172606a&sid=448D7172-0287-4D3C-9A50-EF91CB51EFF8&mid=448D7172-0287-4D3C-9A50-EF91CB51EFF8&ts=1731736396265&proxy=true&sig=1b7c923faf04480ea88c5fedb4239fe147babe10f45a03cdde52e9baa407c9a4";}]}%
```
